# Generated by Django 5.2.3 on 2025-06-26 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
                ('retorno_necessario', models.BooleanField(default=False)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.paciente')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
