# Generated by Django 5.2.3 on 2025-06-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Confirmado', 'Confirmado'), ('Pendente', 'Pendente')], default='Confirmado', max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='core.agendamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
