# Generated by Django 5.2.3 on 2025-06-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agendamento_status_consulta_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='anamnese',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exame_fisico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exames_solicitados',
            field=models.TextField(blank=True),
        ),
    ]
