# Generated by Django 5.2.3 on 2025-06-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consulta_anamnese_consulta_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='consultas/arquivos/')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo')], max_length=10)),
                ('tamanho_mb', models.FloatField(help_text='Tamanho do arquivo em MB')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.consulta')),
            ],
        ),
    ]
