# Generated by Django 5.2.3 on 2025-06-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_arquivoconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Confirmado', 'Confirmado'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Confirmado', max_length=20),
        ),
    ]
