# Generated by Django 5.2.3 on 2025-06-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='analise_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status_analise_ia',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
