# Generated by Django 5.2.3 on 2025-06-29 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tenant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='tenants.client'),
            preserve_default=False,
        ),
    ]
